language: csharp
solution: Flepper.sln
mono: latest
dotnet: 2.0.0
git:
  depth: 3
script:
  - ./build.sh -target=Tests
notifications:
  slack:
    rooms:
      - brasildotnet:hfolzaVNSDEKWPSRU6LgiQyj#flepper
  email:
    recipients:
      - gustavo.ferrazfontes@gmail.com
      - nicolas.tcs@hotmail.com
      - alberto.monteiro@live.com
    on_success: always
    on_failure: always

      